/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard.components.table.frame_edit;

import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import java.sql.*;
import query.connect.Settings;
import query.tool.model.Cost;
import query.tool.model.CostCategory;
import query.tool.query.CostCategoryQuery;
import query.tool.query.CostQuery;
import query.tool.query.UserQuery;

/**
 *
 * @author Admin
 */
public class CostEditFrame extends javax.swing.JFrame {

    private JFrame frame;
    private Connection conn;
    private CostCategoryQuery query;

    private Object[] rowData;
    private List<CostCategory> costCategory;

    public CostEditFrame(Object[] data) {
        this.setUndecorated(true);
        this.getRootPane().setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        initComponents();
        this.frame = this;
        getContentPane().setBackground(Color.white);
        setLocationRelativeTo(null);
        alertExpense.setVisible(false);

        try {
            this.conn = Settings.BuildConnect();
        } catch (SQLException ex) {
            Logger.getLogger(CostEditFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.rowData = data;
        getData();
        setData();
    }

    public void setData() {
        costCategoryChoose.addItem(rowData[2].toString());
        for (CostCategory i : costCategory) {
            if (i.getCostCtgName().equals(rowData[2])) {
                continue;
            }
            costCategoryChoose.addItem(i.getCostCtgName());

        }
        creatorNameBox.setText(rowData[1].toString());
        costIDBox.setText(rowData[0].toString());
        expenseBox.setText(rowData[3].toString());
        dateAddedBox.setText(rowData[4].toString());
    }

    public void getData() {
        try {
            query = new CostCategoryQuery(this.conn);

            costCategory = query.selectCostCategoryList();
        } catch (SQLException ex) {
            Logger.getLogger(CostEditFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        costIDBox = new textfield.swing.TextField();
        creatorNameBox = new textfield.swing.TextField();
        expenseBox = new textfield.swing.TextField();
        dateAddedBox = new textfield.swing.TextField();
        closeBtn = new swing.MyButton();
        costCategoryChoose = new dashboard.components.combobox.Combobox();
        okBtn = new swing.MyButton();
        alertExpense = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 32)); // NOI18N
        jLabel1.setText("Edit Cost Info");

        costIDBox.setEditable(false);
        costIDBox.setText("CostID");
        costIDBox.setLabelText("Cost ID");
        costIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costIDBoxActionPerformed(evt);
            }
        });

        creatorNameBox.setEditable(false);
        creatorNameBox.setText("Contact");
        creatorNameBox.setLabelText("Creator Name");
        creatorNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatorNameBoxActionPerformed(evt);
            }
        });

        expenseBox.setText("Date Added");
        expenseBox.setLabelText("Expense");
        expenseBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseBoxActionPerformed(evt);
            }
        });
        expenseBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                expenseBoxKeyReleased(evt);
            }
        });

        dateAddedBox.setEditable(false);
        dateAddedBox.setText("Discount");
        dateAddedBox.setLabelText("Date Added");
        dateAddedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateAddedBoxActionPerformed(evt);
            }
        });

        closeBtn.setBackground(new java.awt.Color(255, 0, 51));
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setText("Cancel");
        closeBtn.setColor(new java.awt.Color(255, 0, 51));
        closeBtn.setColorOver(new java.awt.Color(255, 102, 102));
        closeBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });

        costCategoryChoose.setLabeText("Cost Category");

        okBtn.setBackground(new java.awt.Color(0, 255, 255));
        okBtn.setForeground(new java.awt.Color(0, 0, 0));
        okBtn.setText("Ok");
        okBtn.setColor(new java.awt.Color(0, 255, 255));
        okBtn.setColorOver(new java.awt.Color(102, 255, 255));
        okBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        okBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okBtnMouseClicked(evt);
            }
        });

        alertExpense.setForeground(new java.awt.Color(255, 0, 51));
        alertExpense.setText("Invalid Expense");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costCategoryChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dateAddedBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(expenseBox, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(creatorNameBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(costIDBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(alertExpense)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(costIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(creatorNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(costCategoryChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(expenseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateAddedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(alertExpense)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void costIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costIDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costIDBoxActionPerformed

    private void creatorNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatorNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creatorNameBoxActionPerformed

    private void expenseBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expenseBoxActionPerformed

    private void dateAddedBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateAddedBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateAddedBoxActionPerformed

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        frame.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void okBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnMouseClicked
        try {
            int userIDCreated = new UserQuery(this.conn).selectUserByName(rowData[1].toString()).get(0).getUserID();
            int costCtgID = 0;
            for (CostCategory i : costCategory) {
                if (i.getCostCtgName().equals(costCategoryChoose.getSelectedItem())) {
                    costCtgID = i.getCostCtgID();
                    break;
                }
            }
            new CostQuery(this.conn).updateCost(new Cost(Integer.valueOf(rowData[0].toString()), userIDCreated, costCtgID, Integer.valueOf(expenseBox.getText()), Date.valueOf(rowData[4].toString())));
        } catch (SQLException ex) {
            Logger.getLogger(CostEditFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        frame.dispose();
    }//GEN-LAST:event_okBtnMouseClicked

    private void expenseBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expenseBoxKeyReleased
        if (!expenseBox.getText().matches("[0-9]+"))
            alertExpense.setVisible(true);
        else{
            alertExpense.setVisible(false);
        }
    }//GEN-LAST:event_expenseBoxKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertExpense;
    private swing.MyButton closeBtn;
    private dashboard.components.combobox.Combobox costCategoryChoose;
    private textfield.swing.TextField costIDBox;
    private textfield.swing.TextField creatorNameBox;
    private textfield.swing.TextField dateAddedBox;
    private textfield.swing.TextField expenseBox;
    private javax.swing.JLabel jLabel1;
    private swing.MyButton okBtn;
    // End of variables declaration//GEN-END:variables
}
