/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard.components.table.frame_edit;

import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import java.sql.*;
import query.connect.Settings;
import query.tool.model.Cost;
import query.tool.model.CostCategory;
import query.tool.model.ShippingProvider;
import query.tool.query.CostCategoryQuery;
import query.tool.query.CostQuery;
import query.tool.query.ShippingProviderQuery;
import query.tool.query.UserQuery;

/**
 *
 * @author Admin
 */
public class UnPaidOrderEditFrame extends javax.swing.JFrame {

    private JFrame frame;
    private Connection conn;
    private ShippingProviderQuery query;

    private Object[] rowData;
    private List<ShippingProvider> shippingCategory;
    private boolean isValid = false;

    public UnPaidOrderEditFrame(Object[] data) {
        this.setUndecorated(true);
        this.getRootPane().setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        initComponents();
        this.frame = this;
        getContentPane().setBackground(Color.white);
        setLocationRelativeTo(null);

        try {
            this.conn = Settings.BuildConnect();
        } catch (SQLException ex) {
            Logger.getLogger(UnPaidOrderEditFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.rowData = data;
        getData();
        setData();
    }

    public void setData() {
        StatusChoose.addItem("UnPaid");
        StatusChoose.addItem("Paid");
        
        shippingChooseBox.addItem(rowData[2].toString());
        for(ShippingProvider i: shippingCategory){
            if(i.getShippingName().equals(rowData[2].toString()))
                continue;
            shippingChooseBox.addItem(i.getShippingName());
        }
        
        customerNameBox.setText(rowData[1].toString());
        orderIDBox.setText(rowData[0].toString());
        dateOrderBox.setText(rowData[4].toString());
        userCreatedBox.setText(rowData[5].toString());
    }

    public void getData() {
        try {
            query = new ShippingProviderQuery(this.conn);

            shippingCategory = query.selectShippingProvider();
        } catch (SQLException ex) {
            Logger.getLogger(UnPaidOrderEditFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        orderIDBox = new textfield.swing.TextField();
        customerNameBox = new textfield.swing.TextField();
        dateOrderBox = new textfield.swing.TextField();
        userCreatedBox = new textfield.swing.TextField();
        closeBtn = new swing.MyButton();
        StatusChoose = new dashboard.components.combobox.Combobox();
        okBtn = new swing.MyButton();
        shippingChooseBox = new dashboard.components.combobox.Combobox();
        alertQuantity = new javax.swing.JLabel();
        alertFixedPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 32)); // NOI18N
        jLabel1.setText("Edit Order Info");

        orderIDBox.setEditable(false);
        orderIDBox.setText("CostID");
        orderIDBox.setLabelText("Order ID");
        orderIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIDBoxActionPerformed(evt);
            }
        });

        customerNameBox.setEditable(false);
        customerNameBox.setText("Contact");
        customerNameBox.setLabelText("Customer Name");
        customerNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameBoxActionPerformed(evt);
            }
        });

        dateOrderBox.setText("Date Added");
        dateOrderBox.setLabelText("Date Order");
        dateOrderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOrderBoxActionPerformed(evt);
            }
        });
        dateOrderBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateOrderBoxKeyReleased(evt);
            }
        });

        userCreatedBox.setEditable(false);
        userCreatedBox.setText("Discount");
        userCreatedBox.setLabelText("User Created");
        userCreatedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCreatedBoxActionPerformed(evt);
            }
        });

        closeBtn.setBackground(new java.awt.Color(255, 0, 51));
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setText("Cancel");
        closeBtn.setColor(new java.awt.Color(255, 0, 51));
        closeBtn.setColorOver(new java.awt.Color(255, 102, 102));
        closeBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });

        StatusChoose.setLabeText("Status");

        okBtn.setBackground(new java.awt.Color(0, 255, 255));
        okBtn.setForeground(new java.awt.Color(0, 0, 0));
        okBtn.setText("Ok");
        okBtn.setColor(new java.awt.Color(0, 255, 255));
        okBtn.setColorOver(new java.awt.Color(102, 255, 255));
        okBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        okBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okBtnMouseClicked(evt);
            }
        });
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        shippingChooseBox.setLabeText("Shipping Name");

        alertQuantity.setForeground(new java.awt.Color(255, 0, 51));
        alertQuantity.setText("Quantity must be greater than or equal to 1");

        alertFixedPrice.setForeground(new java.awt.Color(255, 0, 51));
        alertFixedPrice.setText("Fixed must be greater than 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 574, Short.MAX_VALUE)
                        .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alertQuantity)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(StatusChoose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(shippingChooseBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(orderIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(customerNameBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(userCreatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dateOrderBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(alertFixedPrice))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userCreatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOrderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(shippingChooseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(StatusChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(alertQuantity)
                .addGap(18, 18, 18)
                .addComponent(alertFixedPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderIDBoxActionPerformed

    private void customerNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameBoxActionPerformed

    private void dateOrderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOrderBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOrderBoxActionPerformed

    private void userCreatedBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCreatedBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userCreatedBoxActionPerformed

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        frame.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void okBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnMouseClicked
        if (isValid) {
            okBtn.setEnabled(true);
            try {
                int userIDCreated = new UserQuery(this.conn).selectUserByName(rowData[1].toString()).get(0).getUserID();
                int costCtgID = 0;
//                for (CostCategory i : shippingCategory) {
//                    if (i.getCostCtgName().equals(StatusChoose.getSelectedItem())) {
//                        costCtgID = i.getCostCtgID();
//                        break;
//                    }
//                }
                new CostQuery(this.conn).updateCost(new Cost(Integer.valueOf(rowData[0].toString()), userIDCreated, costCtgID, Integer.valueOf(dateOrderBox.getText()), Date.valueOf(rowData[4].toString())));
            } catch (SQLException ex) {
                Logger.getLogger(UnPaidOrderEditFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            frame.dispose();
        }
    }//GEN-LAST:event_okBtnMouseClicked

    private void dateOrderBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateOrderBoxKeyReleased
        
    }//GEN-LAST:event_dateOrderBoxKeyReleased

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed

    }//GEN-LAST:event_okBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dashboard.components.combobox.Combobox StatusChoose;
    private javax.swing.JLabel alertFixedPrice;
    private javax.swing.JLabel alertQuantity;
    private swing.MyButton closeBtn;
    private textfield.swing.TextField customerNameBox;
    private textfield.swing.TextField dateOrderBox;
    private javax.swing.JLabel jLabel1;
    private swing.MyButton okBtn;
    private textfield.swing.TextField orderIDBox;
    private dashboard.components.combobox.Combobox shippingChooseBox;
    private textfield.swing.TextField userCreatedBox;
    // End of variables declaration//GEN-END:variables
}
