/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import dialog.message.AlertDialog;
import dialog.message.MessageDialog;
import java.sql.*;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import query.connect.Settings;
import query.tool.GeneralQuery;

/**
 *
 * @author RAVEN
 */
public class Recovery extends javax.swing.JPanel {

    private Connection conn = null;
    private JFrame frame;

    public Recovery(JFrame frame) {
        this.frame = frame;
        initComponents();
        alert.setVisible(false);
        findAccountBtn.setVisible(true);
        try {
            this.conn = Settings.BuildConnect();
        } catch (SQLException ex) {
            Logger.getLogger(Recovery.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void register() {
        recoveryKeyTxt.grabFocus();
    }

    public void addEventBackLogin(ActionListener event) {
        cmdBackLogin.addActionListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recoveryKeyTxt = new swing.MyTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        findAccountBtn = new swing.MyButton();
        cmdBackLogin = new javax.swing.JButton();
        alert = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        recoveryKeyTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                recoveryKeyTxtFocusLost(evt);
            }
        });

        jLabel1.setText("Recovery Key");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(69, 68, 68));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Recovery");

        findAccountBtn.setBackground(new java.awt.Color(125, 229, 251));
        findAccountBtn.setForeground(new java.awt.Color(40, 40, 40));
        findAccountBtn.setText("Find account");
        findAccountBtn.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        findAccountBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findAccountBtnMouseClicked(evt);
            }
        });
        findAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findAccountBtnActionPerformed(evt);
            }
        });

        cmdBackLogin.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        cmdBackLogin.setForeground(new java.awt.Color(30, 122, 236));
        cmdBackLogin.setText("← Back to Login");
        cmdBackLogin.setContentAreaFilled(false);
        cmdBackLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdBackLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBackLoginActionPerformed(evt);
            }
        });

        alert.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        alert.setForeground(new java.awt.Color(255, 0, 51));
        alert.setText("No recovery key found");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recoveryKeyTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(cmdBackLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alert, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addComponent(findAccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(recoveryKeyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(alert)
                .addGap(18, 18, 18)
                .addComponent(findAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdBackLogin)
                .addGap(145, 145, 145))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void findAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findAccountBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findAccountBtnActionPerformed

    private void findAccountBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findAccountBtnMouseClicked
        try {
            if (conn == null) {
                Settings.TryGetConnection(frame, conn);
            }
            GeneralQuery query = new GeneralQuery(conn);

            List<String> account = new ArrayList<>();
            account = query.getUserAuth(recoveryKeyTxt.getText());
            //System.out.println(account);
            if (account != null) {
                AlertDialog dialog = new AlertDialog(frame);
                dialog.showMessage("Your Account Info", "Username: " + account.get(0) + "\n Password: " + account.get(1));
                if (dialog.getMessageType().equals(MessageDialog.MessageType.OK)) {
                }
            } else {
                alert.setVisible(true);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_findAccountBtnMouseClicked

    private void cmdBackLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBackLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdBackLoginActionPerformed

    private void recoveryKeyTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_recoveryKeyTxtFocusLost
        // TODO add your\        recoveryKey =;
    }//GEN-LAST:event_recoveryKeyTxtFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JButton cmdBackLogin;
    private swing.MyButton findAccountBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private swing.MyTextField recoveryKeyTxt;
    // End of variables declaration//GEN-END:variables
}
