/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard.components.table.frame_view;

import java.awt.Color;
import java.sql.*;
import java.util.Arrays;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import query.connect.Settings;
import query.tool.model.Cost;
import query.tool.model.CostCategory;
import query.tool.model.User;
import query.tool.query.CustomerQuery;
import query.tool.query.DiscountQuery;

/**
 *
 * @author Admin
 */
public class CostViewFrame extends javax.swing.JFrame {

    private Connection conn;
    private JFrame frame;
    private CustomerQuery queryC;
    private DiscountQuery queryD;

    private Object[] rowData;
    
    public CostViewFrame(Object[] data) {
        this.setUndecorated(true);
        this.getRootPane().setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        initComponents();
        this.frame = this;
        getContentPane().setBackground(Color.white);
        setLocationRelativeTo(null);

        this.rowData = data;
        setData();
    }


    public void setData() {
        costCtgBox.setText(rowData[2].toString());
        creatorNameBox.setText(rowData[1].toString());
        costIDBox.setText(rowData[0].toString());
        expenseBox.setText(rowData[3].toString());
        dateAddedBox.setText(rowData[4].toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        costIDBox = new textfield.swing.TextField();
        creatorNameBox = new textfield.swing.TextField();
        costCtgBox = new textfield.swing.TextField();
        expenseBox = new textfield.swing.TextField();
        dateAddedBox = new textfield.swing.TextField();
        closeBtn = new swing.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 32)); // NOI18N
        jLabel1.setText("Cost Info");

        costIDBox.setEditable(false);
        costIDBox.setText("CostID");
        costIDBox.setLabelText("Cost ID");
        costIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costIDBoxActionPerformed(evt);
            }
        });

        creatorNameBox.setEditable(false);
        creatorNameBox.setText("Contact");
        creatorNameBox.setLabelText("Creator Name");
        creatorNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatorNameBoxActionPerformed(evt);
            }
        });

        costCtgBox.setEditable(false);
        costCtgBox.setText("Address");
        costCtgBox.setLabelText("Cost Category");
        costCtgBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costCtgBoxActionPerformed(evt);
            }
        });

        expenseBox.setEditable(false);
        expenseBox.setText("Date Added");
        expenseBox.setLabelText("Expense");
        expenseBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseBoxActionPerformed(evt);
            }
        });

        dateAddedBox.setEditable(false);
        dateAddedBox.setText("Discount");
        dateAddedBox.setLabelText("Date Added");
        dateAddedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateAddedBoxActionPerformed(evt);
            }
        });

        closeBtn.setForeground(new java.awt.Color(0, 0, 0));
        closeBtn.setText("Ok");
        closeBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dateAddedBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(expenseBox, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                        .addComponent(costCtgBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(creatorNameBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(costIDBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(costIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(creatorNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(costCtgBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(expenseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateAddedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void costIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costIDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costIDBoxActionPerformed

    private void creatorNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatorNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creatorNameBoxActionPerformed

    private void costCtgBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costCtgBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costCtgBoxActionPerformed

    private void expenseBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expenseBoxActionPerformed

    private void dateAddedBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateAddedBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateAddedBoxActionPerformed

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        frame.dispose();
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.MyButton closeBtn;
    private textfield.swing.TextField costCtgBox;
    private textfield.swing.TextField costIDBox;
    private textfield.swing.TextField creatorNameBox;
    private textfield.swing.TextField dateAddedBox;
    private textfield.swing.TextField expenseBox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
