/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard.components.table.frame_view;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class ProductViewFrame extends javax.swing.JFrame {
    private JFrame frame;

    private Object[] rowData;
    
    public ProductViewFrame(Object[] data) {
        this.setUndecorated(true);
        this.getRootPane().setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        initComponents();
        this.frame = this;
        getContentPane().setBackground(Color.white);
        setLocationRelativeTo(null);

        this.rowData = data;
        setData();
    }


    public void setData() {
        productIDBox.setText(rowData[0].toString());
    productNameBox.setText(rowData[1].toString());
    inStockQuantityBox.setText(rowData[2].toString());
    priceBox.setText(rowData[3].toString());
    productCategoryBox.setText(rowData[4].toString());
    dateAddedBox.setText(rowData[5].toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        productIDBox = new textfield.swing.TextField();
        productNameBox = new textfield.swing.TextField();
        inStockQuantityBox = new textfield.swing.TextField();
        productCategoryBox = new textfield.swing.TextField();
        dateAddedBox = new textfield.swing.TextField();
        closeBtn = new swing.MyButton();
        priceBox = new textfield.swing.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 32)); // NOI18N
        jLabel1.setText("Product Info");

        productIDBox.setEditable(false);
        productIDBox.setText("CostID");
        productIDBox.setLabelText("Product ID");
        productIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIDBoxActionPerformed(evt);
            }
        });

        productNameBox.setEditable(false);
        productNameBox.setText("Contact");
        productNameBox.setLabelText("Product Name");
        productNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameBoxActionPerformed(evt);
            }
        });

        inStockQuantityBox.setEditable(false);
        inStockQuantityBox.setText("Address");
        inStockQuantityBox.setLabelText("In Stock Quantity");
        inStockQuantityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inStockQuantityBoxActionPerformed(evt);
            }
        });

        productCategoryBox.setEditable(false);
        productCategoryBox.setText("Date Added");
        productCategoryBox.setLabelText("Product Category");
        productCategoryBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCategoryBoxActionPerformed(evt);
            }
        });

        dateAddedBox.setEditable(false);
        dateAddedBox.setText("Discount");
        dateAddedBox.setLabelText("Date Added");
        dateAddedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateAddedBoxActionPerformed(evt);
            }
        });

        closeBtn.setForeground(new java.awt.Color(0, 0, 0));
        closeBtn.setText("Ok");
        closeBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });

        priceBox.setEditable(false);
        priceBox.setText("Date Added");
        priceBox.setLabelText("Price");
        priceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dateAddedBox, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                                    .addComponent(inStockQuantityBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productNameBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(productIDBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(productCategoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(productIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inStockQuantityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(priceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productCategoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateAddedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDBoxActionPerformed

    private void productNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameBoxActionPerformed

    private void inStockQuantityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inStockQuantityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inStockQuantityBoxActionPerformed

    private void productCategoryBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCategoryBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productCategoryBoxActionPerformed

    private void dateAddedBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateAddedBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateAddedBoxActionPerformed

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        frame.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void priceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.MyButton closeBtn;
    private textfield.swing.TextField dateAddedBox;
    private textfield.swing.TextField inStockQuantityBox;
    private javax.swing.JLabel jLabel1;
    private textfield.swing.TextField priceBox;
    private textfield.swing.TextField productCategoryBox;
    private textfield.swing.TextField productIDBox;
    private textfield.swing.TextField productNameBox;
    // End of variables declaration//GEN-END:variables
}
